### ISSUE TITLE
[FEATURE - web] Edit Info page(Kakao map, Main poster, Credit)

### ISSUE THREAD

**Issue by JaeIL00** [2022-WWW-Project-Front/www-web#33]
## Description
인포페이지 최종 마무리
카카오맵은 사용자가 우리 서비스내에서 벗어나지 않도록 다이나믹 맵 옵션을 살리고 장소 링크를 삭제한다.
크레딧은 운영진의 링크트리와 뷰포트 사이즈에 맞는 레이아웃 스타일을 적용한다.

## Todo
- [x] main 포스터를 삽입
- [x] 카카오맵 옵션 변경
- [x] 크레딧 스타일 변경
- [x] 폰트 다운로드 소스 삽입
